export const previewItems = [
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product1.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product2.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product3.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product4.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product5.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product6.webp",
    price: 199,
  },
];
export const breakPointsPreview = {
  1298: {
    slidesPerView: 3.5,
    spaceBetween: 15,
  },
  1024: {
    slidesPerView: 2.8,
    spaceBetween: 15,
  },
  768: {
    slidesPerView: 2.3,
    spaceBetween: 15,
  },
  640: {
    slidesPerView: 2.9,
    spaceBetween: 10,
  },
  468: {
    slidesPerView: 2.6,
    spaceBetween: 10,
  },
  360: {
    slidesPerView: 2.2,
    spaceBetween: 8,
  },
};
export const newThisWeek = [
  {
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/week/product1.webp",
    price: 199,
  },
  {
    title: "Basic Slim Fit T-Shirt",
    type: "Cotton T Shirt",
    thumbnail: "/collection/week/product2.webp",
    price: 199,
  },
  {
    title: "Blurred Print T-Shirt",
    type: "Henley T-Shirt",
    thumbnail: "/collection/week/product3.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Crewneck T-Shirt",
    thumbnail: "/collection/week/product4.webp",
    price: 199,
  },
  {
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/week/product1.webp",
    price: 199,
  },
];
export const breakPointsWeek = {
  1298: {
    slidesPerView: 4.5,
    spaceBetween: 30,
  },
  768: {
    slidesPerView: 3.6,
    spaceBetween: 15,
  },
  640: {
    slidesPerView: 2.9,
    spaceBetween: 10,
  },
  468: {
    slidesPerView: 2.6,
    spaceBetween: 10,
  },
  360: {
    slidesPerView: 2.2,
    spaceBetween: 8,
  },
};

export const xivCollection = [
  {
    id: 1,
    title: "Basic Heavy Weight T-shirt",
    type: "cotton t-shirt",
    thumbnail: "/collection/product9.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
    colors: [
      { color: "d9d9d9", name: "lightgray" },
      { color: "1e1e1e7d", name: "gray" },
      { color: "1e1e1e", name: "black" },
      { color: "f1f1f1", name: "white" },
    ],
  },
  {
    id: 2,
    title: "Embroidered Seersucker Shirt",
    type: "rounded-neck t-shirt",
    thumbnail: "/collection/product8.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { color: "b9c1e8", name: "lightblue	" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 3,
    title: "Basic Polo T-Shirt",
    type: "rounded-neck t-shirt",
    thumbnail: "/collection/product7.webp",
    price: 1949,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { color: "800080", name: "purple" },
      { color: "008000", name: "green" },
      { color: "a5d6ca", name: "teal" },
    ],
  },
  {
    id: 4,
    title: "Full Sleeve Zipper",
    type: "crewneck t-shirt",
    thumbnail: "/collection/product6.webp",
    price: 199,
    available: false,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
    colors: [
      { color: "b9c1e8", name: "lightblue	" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 5,
    title: "Embroidered Seersucker Shirt",
    type: "c-neck t-shirt",
    thumbnail: "/collection/product5.webp",
    price: 199,
    available: false,
    rate: 0,
    category: "men",
    sizes: ["M", "L", "XL", "2X"],
    colors: [
      { color: "008000", name: "green" },
      { color: "a5d6ca", name: "teal" },
      { color: "000080", name: "blue" },
    ],
  },
  {
    id: 6,
    title: "Embroidered Seersucker Shirt",
    type: "oversize t-shirt",
    thumbnail: "/collection/product4.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["XS", "M", "L", "XL", "2X"],
    colors: [
      { color: "008080", name: "emerald" },
      { color: "8a2be2", name: "lightpurple" },
      { color: "ff8c00", name: "orange" },
      { color: "ffd700", name: "yellow" },
    ],
  },
  {
    id: 7,
    title: "Embroidered Seersucker Jacket",
    type: "caught jacket",
    thumbnail: "/collection/product3.webp",
    price: 199,
    available: false,
    rate: 0,
    category: "men",
    sizes: ["M", "L", "XL"],
    colors: [
      { color: "1e1e1e", name: "black" },
      { color: "f1f1f1", name: "white" },
      { color: "b9c1e8", name: "lightblue	" },
    ],
  },
  {
    id: 8,
    title: "oversize seersucker t-shirt",
    type: "oversize t-shirt",
    thumbnail: "/collection/product2.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["M", "L", "XL"],
    colors: [
      { color: "b9c1e8", name: "lightblue	" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 9,
    title: "k-cloth trouser",
    type: "cloth trouser",
    thumbnail: "/collection/product1.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
    colors: [
      { color: "008000", name: "green" },
      { color: "a5d6ca", name: "teal" },
      { color: "000080", name: "blue" },
      { color: "008080", name: "emerald" },
      { color: "8a2be2", name: "lightpurple" },
    ],
  },
  {
    id: 10,
    title: "Crunchy Jean Jacket",
    type: "crunch jacket",
    thumbnail: "/collection/product10.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
    colors: [
      { color: "ff8c00", name: "orange" },
      { color: "ffd700", name: "yellow" },
      { color: "e9967a", name: "lightred" },
      { color: "2f4f4f", name: "olive" },
      { color: "cd5c5c", name: "kashmir" },
    ],
  },
  {
    id: 11,
    title: "Long sleeved T-shirt",
    type: "sleeved t-shirt",
    thumbnail: "/collection/product11.webp",
    price: 199,
    available: false,
    rate: 0,
    category: "men",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { color: "b9c1e8", name: "lightblue	" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 12,
    title: "baseball Seersucker Jacket",
    type: "baseball jacket",
    thumbnail: "/collection/product12.webp",
    price: 199,
    available: false,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L"],
    colors: [
      { color: "ff8c00", name: "orange" },
      { color: "ffd700", name: "yellow" },
      { color: "e9967a", name: "lightred" },
      { color: "2f4f4f", name: "olive" },
      { color: "cd5c5c", name: "kashmir" },
    ],
  },
  {
    id: 13,
    title: "Oversize Seersucker T-Shirt",
    type: "oversize t-shirt",
    thumbnail: "/collection/product19.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "men",
    sizes: ["S", "M", "L"],
    colors: [
      { color: "a5d6ca", name: "teal" },
      { color: "000080", name: "blue" },
      { color: "008080", name: "emerald" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 14,
    title: "Heavy Seersucker Coat",
    type: "heavy coat",
    thumbnail: "/collection/product20.avif",
    price: 199,
    available: false,
    rate: 0,
    category: "women",
    sizes: ["S", "M", "L"],
    colors: [
      { color: "1e1e1e", name: "black" },
      { color: "f1f1f1", name: "white" },
      { color: "b9c1e8", name: "lightblue	" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 15,
    title: "Sporty Seersucker Suit",
    type: "Sporty suit",
    thumbnail: "/collection/product21.avif",
    price: 199,
    available: false,
    rate: 0,
    category: "women",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { color: "b9c1e8", name: "lightblue	" },
      { color: "e9967a", name: "lightred" },
      { color: "2f4f4f", name: "olive" },
      { color: "cd5c5c", name: "kashmir" },
    ],
  },
  {
    id: 16,
    title: "comfortable sportswear",
    type: "training sport wear",
    thumbnail: "/collection/product15.webp",
    price: 199,
    available: true,
    rate: 0,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { color: "800000", name: "red" },
      { color: "a5d6ca", name: "teal" },
      { color: "000080", name: "blue" },
      { color: "008080", name: "emerald" },
      { color: "8a2be2", name: "lightpurple" },
    ],
  },
  {
    id: 17,
    title: "Women Sweat Shirt",
    type: "oversize sweat-shirt",
    thumbnail: "/collection/product16.webp",
    price: 199,
    available: false,
    rate: 0,
    rate: 0,
    category: "women",
    sizes: ["M", "L", "XL"],
    colors: [
      { color: "b9c1e8", name: "lightblue" },
      { color: "ffe4b5", name: "sugar" },
      { color: "800000", name: "red" },
      { color: "800080", name: "purple" },
    ],
  },
  {
    id: 18,
    title: "Women Sweat Shirt",
    type: "oversize sweat-shirt",
    thumbnail: "/collection/product17.webp",
    price: 199,
    available: true,
    category: "women",
    sizes: ["M", "L", "XL", "2XL"],
    colors: [
      { color: "800000", name: "red" },
      { color: "b9c1e8", name: "lightblue" },
      { color: "ffe4b5", name: "sugar" },
      { color: "008000", name: "green" },
      { color: "800080", name: "purple" },
    ],
  },
];
export const fashion = [
  "/collection/fashion/pic-1.webp",
  "/collection/fashion/pic-2.webp",
  "/collection/product1.webp",
  "/collection/fashion/pic-4.webp",
];
