export const previewItems = [
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product1.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product2.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product3.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product4.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product5.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product6.webp",
    price: 199,
  },
];
export const breakPointsPreview = {
  1298: {
    slidesPerView: 3.5,
    spaceBetween: 15,
  },
  1024: {
    slidesPerView: 2.8,
    spaceBetween: 15,
  },
  768: {
    slidesPerView: 2.3,
    spaceBetween: 15,
  },
  640: {
    slidesPerView: 2.9,
    spaceBetween: 10,
  },
  468: {
    slidesPerView: 2.6,
    spaceBetween: 10,
  },
  360: {
    slidesPerView: 2.2,
    spaceBetween: 8,
  },
};
export const newThisWeek = [
  {
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/week/product1.webp",
    price: 199,
  },
  {
    title: "Basic Slim Fit T-Shirt",
    type: "Cotton T Shirt",
    thumbnail: "/collection/week/product2.webp",
    price: 199,
  },
  {
    title: "Blurred Print T-Shirt",
    type: "Henley T-Shirt",
    thumbnail: "/collection/week/product3.webp",
    price: 199,
  },
  {
    title: "Full Sleeve Zipper",
    type: "Crewneck T-Shirt",
    thumbnail: "/collection/week/product4.webp",
    price: 199,
  },
  {
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/week/product1.webp",
    price: 199,
  },
];
export const breakPointsWeek = {
  1298: {
    slidesPerView: 4.5,
    spaceBetween: 30,
  },
  768: {
    slidesPerView: 3.6,
    spaceBetween: 15,
  },
  640: {
    slidesPerView: 2.9,
    spaceBetween: 10,
  },
  468: {
    slidesPerView: 2.6,
    spaceBetween: 10,
  },
  360: {
    slidesPerView: 2.2,
    spaceBetween: 8,
  },
};
export const xivCollection = [
  {
    id: 1,
    title: "Basic Heavy Weight T-shirt",
    type: "Cotton T Shirt",
    thumbnail: "/collection/product9.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
  },
  {
    id: 2,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product8.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    title: "Basic Heavy Weight T-shirt",
    type: "Henley T-Shirt",
    thumbnail: "/collection/product7.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 4,
    title: "Full Sleeve Zipper",
    type: "Crewneck T-Shirt",
    thumbnail: "/collection/product6.webp",
    price: 199,
    available: false,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
  },
  {
    id: 5,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product5.webp",
    price: 199,
    available: false,
    category: "men",
    sizes: ["M", "L", "XL", "2X"],
  },
  {
    id: 6,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product4.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["XS", "M", "L", "XL", "2X"],
  },
  {
    id: 7,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product3.webp",
    price: 199,
    available: false,
    category: "men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 8,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product2.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 9,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product1.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
  },
  {
    id: 10,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product10.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L", "XL", "2X"],
  },
  {
    id: 11,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product11.webp",
    price: 199,
    available: false,
    category: "men",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 12,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product12.webp",
    price: 199,
    available: false,
    category: "men",
    sizes: ["S", "M", "L"],
  },
  {
    id: 13,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product19.webp",
    price: 199,
    available: true,
    category: "men",
    sizes: ["S", "M", "L"],
  },
  {
    id: 14,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product20.avif",
    price: 199,
    available: false,
    category: "women",
    sizes: ["S", "M", "L"],
  },
  {
    id: 15,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product21.avif",
    price: 199,
    available: false,
    category: "women",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 16,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product15.webp",
    price: 199,
    available: true,
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 17,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product16.webp",
    price: 199,
    available: false,
    category: "women",
    sizes: ["M", "L", "XL"],
  },
  {
    id: 18,
    title: "Embroidered Seersucker Shirt",
    type: "V-Neck T-Shirt",
    thumbnail: "/collection/product17.webp",
    price: 199,
    available: true,
    category: "women",
    sizes: ["M", "L", "XL", "2XL"],
  },
];
export const fashion = [
  "/collection/fashion/pic-1.webp",
  "/collection/fashion/pic-2.webp",
  "/collection/product1.webp",
  "/collection/fashion/pic-4.webp",
];
